'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Item={id:string;subject:string;topic:string;scheduled_for:string;interval_days:number;repetition_count:number;status:string};
export default function Revision(){
 const[items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/revision',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error??'Could not load revision queue');return}setItems(d.items??[])}
 useEffect(()=>{load()},[]);
 async function review(id:string,rating:number){setBusy(id);setError('');try{const r=await fetch('/api/revision',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,rating})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Review failed');await load()}catch(e){setError(e instanceof Error?e.message:'Review failed')}finally{setBusy('')}}
 const today=new Date().toISOString().slice(0,10),due=items.filter(x=>x.scheduled_for<=today),upcoming=items.filter(x=>x.scheduled_for>today);
 return <main className="min-h-screen bg-slate-950 p-4 text-white sm:p-6"><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="text-sm text-blue-300">← Dashboard</Link><h1 className="mt-7 text-3xl font-bold sm:text-4xl">🔁 Revision Engine</h1><p className="mt-2 text-slate-400">Adaptive revision based on how well you remember each topic.</p>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat t="Due today" v={due.length}/><Stat t="Upcoming" v={upcoming.length}/><Stat t="Scheduled" v={items.length}/></div><section className="mt-7 rounded-3xl border border-white/10 bg-white/[0.03] p-5"><h2 className="text-xl font-bold">📌 Today's Revision</h2>{due.length===0?<p className="mt-4 text-slate-500">No revision due today. Great work!</p>:<div className="mt-4 space-y-3">{due.map(x=><ItemCard key={x.id} item={x} busy={busy===x.id} onReview={review}/>)}</div>}</section><section className="mt-7"><h2 className="text-xl font-bold">Upcoming</h2><div className="mt-3 space-y-2">{upcoming.map(x=><div key={x.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="font-semibold">{x.subject} · {x.topic}</p><p className="text-xs text-slate-500">{x.scheduled_for} · interval {x.interval_days} day(s) · {x.repetition_count} reviews</p></div>)}{upcoming.length===0&&<p className="text-sm text-slate-500">No upcoming revisions yet.</p>}</div></section></div></main>}
function Stat({t,v}:{t:string;v:number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-sm text-slate-400">{t}</p><p className="mt-1 text-3xl font-bold">{v}</p></div>}
function ItemCard({item,busy,onReview}:{item:Item;busy:boolean;onReview:(id:string,r:number)=>void}){return <div className="rounded-2xl border border-white/10 bg-slate-900 p-4"><p className="font-semibold">{item.subject} · {item.topic}</p><p className="mt-1 text-xs text-slate-500">{item.repetition_count} previous review(s) · current interval {item.interval_days} day(s)</p><div className="mt-4 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(r=><button key={r} disabled={busy} onClick={()=>onReview(item.id,r)} className="rounded-xl border border-white/10 bg-white/5 px-2 py-3 text-xs hover:bg-white/10 disabled:opacity-40">{r===1?'😟':r===2?'😕':r===3?'😐':r===4?'🙂':'😎'}<br/>{r}</button>)}</div><p className="mt-2 text-center text-[11px] text-slate-600">1 = forgot · 5 = mastered</p></div>}
